//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESMART_HMS.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BarItem
    {
        public string Id { get; set; }
        public string BarItemId { get; set; }
        public string ItemName { get; set; }
        public int Quantity { get; set; }
        public string Type { get; set; }
        public string Measurement { get; set; }
        public string CreatedBy { get; set; }
        public bool IsTrashed { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
        public string Barcode { get; set; }
        public decimal CostPrice { get; set; }
        public Nullable<decimal> SellingPrice { get; set; }
    
        public virtual ApplicationUser ApplicationUser { get; set; }
    }
}
