//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESMART_HMS.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChartOfAccount
    {
        public string Id { get; set; }
        public string AccountCode { get; set; }
        public string AccountName { get; set; }
        public string AccountType { get; set; }
        public string AccountGroup { get; set; }
        public bool IsActive { get; set; }
        public bool IsTrashed { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
        public string RollTo { get; set; }
        public Nullable<bool> RollBalance { get; set; }
        public Nullable<bool> CashflowAccount { get; set; }
    
        public virtual ApplicationUser ApplicationUser { get; set; }
    }
}
