//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESMART_HMS.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyInformation
    {
        public string Id { get; set; }
        public string CompanyId { get; set; }
        public string Name { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public string WebsiteURL { get; set; }
        public string TaxNumber { get; set; }
        public string NoOfEmployees { get; set; }
        public byte[] Logo { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
    }
}
