//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESMART_HMS.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class GuestCard
    {
        public string Id { get; set; }
        public string CardNo { get; set; }
        public string CardType { get; set; }
        public System.DateTime IssueTime { get; set; }
        public System.DateTime RefundTime { get; set; }
        public string IssuedBy { get; set; }
        public bool CanOpenDeadLocks { get; set; }
        public bool PassageMode { get; set; }
        public bool IsTrashed { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
    
        public virtual ApplicationUser ApplicationUser { get; set; }
    }
}
