//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESMART_HMS.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public string Id { get; set; }
        public string MenuItemId { get; set; }
        public int InitialStock { get; set; }
        public int CurrentStock { get; set; }
        public int LowStockThreshold { get; set; }
        public string CreatedBy { get; set; }
        public bool IsTrashed { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
    
        public virtual ApplicationUser ApplicationUser { get; set; }
        public virtual MenuItem MenuItem { get; set; }
    }
}
