//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESMART_HMS.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public string Id { get; set; }
        public string InvoiceId { get; set; }
        public string GuestId { get; set; }
        public string BookingId { get; set; }
        public System.DateTime Date { get; set; }
        public decimal TotalAmount { get; set; }
        public Nullable<decimal> VATAmount { get; set; }
        public string Status { get; set; }
        public bool IsTrashed { get; set; }
    
        public virtual Booking Booking { get; set; }
        public virtual Guest Guest { get; set; }
    }
}
