//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESMART_HMS.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LicenseInfo
    {
        public string Id { get; set; }
        public string HotelName { get; set; }
        public string ProductKey { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
    }
}
