//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESMART_HMS.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public string Id { get; set; }
        public string OrderId { get; set; }
        public string CustomerId { get; set; }
        public System.DateTime OrderDate { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public string ItemId { get; set; }
        public int Quantity { get; set; }
        public bool IsTrashed { get; set; }
        public string IssuedBy { get; set; }
    
        public virtual ApplicationUser ApplicationUser { get; set; }
        public virtual Guest Guest { get; set; }
        public virtual MenuItem MenuItem { get; set; }
    }
}
