//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESMART_HMS.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderItem()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public string Id { get; set; }
        public string OrderItemId { get; set; }
        public string ItemId { get; set; }
        public int Quantity { get; set; }
        public System.DateTime OrderDate { get; set; }
        public Nullable<decimal> ItemPrice { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public bool IsTrashed { get; set; }
        public string IssuedBy { get; set; }
    
        public virtual ApplicationUser ApplicationUser { get; set; }
        public virtual MenuItem MenuItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
