//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESMART_HMS.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public string Id { get; set; }
        public string TransactionId { get; set; }
        public string GuestId { get; set; }
        public string ServiceId { get; set; }
        public System.DateTime Date { get; set; }
        public decimal Amount { get; set; }
        public string Status { get; set; }
        public string Description { get; set; }
        public string Type { get; set; }
        public bool IsTrashed { get; set; }
    
        public virtual Guest Guest { get; set; }
    }
}
