//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESMART_HMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        public string Id { get; set; }
        public string RoomId { get; set; }
        public string RoomName { get; set; }
        public string RoomCardNo { get; set; }
        public string RoomLockNo { get; set; }
        public string RoomTypeId { get; set; }
        public int AdultPerRoom { get; set; }
        public int ChildrenPerRoom { get; set; }
        public string Description { get; set; }
        public decimal Rate { get; set; }
        public bool IsAvailable { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
    
        public virtual RoomType RoomType { get; set; }
    }
}
